version: '3.8'

services:
  app:
    build: ./app
    container_name: app
    ports:
      - "3000:3000"

  test:
    build: ./test
    container_name: test
    depends_on:
      - app
    network_mode: service:app
